services:

  server:
    container_name: server
    build: .
    restart: always
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=&I1QBg^C@Int
      - DB_NAME=main
      - JWT_SECRET=fanscrm-jwt-secret-key
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:3306", "--timeout=60", "-s", "--", "npm", "run", "start:prod"]

  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=&I1QBg^C@Int
      - MYSQL_DATABASE=main